'use strict';
angular.module('enTranslation', []).config(function($translateProvider) {
    $translateProvider
        .translations('es', {
            'ADISTAL_NOTIFICATION': 'Notificación de ADISTAL',
            'ABDOMEN_PELVIS': 'Abdomen y Pelvis',
            'ACCEPT': 'Aceptar',
            'ACCEPT_CALL': 'Aceptar Llamada',
            'ACTIONS': 'Acciones',
            'ABDOMEN_AND_PELVIS': 'Abdomen y pelvis',
            'ADDRESS': 'Dirección',
            'ADD': 'Agregar',
            'ADD_FILE': 'Agregar Archivo',
            'ADD_YOUR_NOTE_HERE': 'Agregue su nota aquí',
            'ADMIN': 'Administrador',
            'ADULT_DISEASES': 'Enfermedades de la edad adulta',
            'ALCOHOLISM': 'Alcoholismo',
            'ASSIGN': 'Asignar',
            'ASAP': 'Asap',
            'ASSIGN_SPECIALTY': 'Asignar especialidad',
            'AGE': 'Edad',
            'ANEMIA': 'Anemia',
            'ASTHMA_ADULTHOOD': 'Asma',
            'ASTHMA_CHILLHOOD': 'Asma',
            'ASYNCHRONOUS': 'Asincrónica',
            'ASYNCHRONOUS_CONSULTATION': 'Consulta Asincrónica',
            'APPARATUS_GENITO_URINARIO': 'Aparato Genito Urinario',
            'APPOINTMENTS': 'citas',
            'APPOINTMENT_DATE': 'Fecha de la cita',
            'ARE_YOU_SURE_YOU_WANT_TO_DISCARD_THIS_REQUEST': '¿Está seguro que desea descartar esta solicitud?',
            'ARE_YOU_SURE_YOU_WANT_TO_DISCARD_THIS_REPORT': '¿Está seguro que desea descartar este reporte?',
            'answered': 'Respondida',
            'ANSWEREDBY': 'Respondido por',
            'AUTHOR': 'Autor',
            'AUXILIAR': 'Auxiliar',
            'ARE_YOU_SURE_YOU_WANT_TO_DELETE_THE_USER': '¿Esta seguro que desea eliminar el usuario?',
            'ARE_YOU_SURE_YOU_WANT_TO_DELETE_THE_RECORD': '¿Esta seguro que desea eliminar el registro?',
            'ARE_YOU_SURE_YOU_WANT_TO_HIDE_THE_RECORD': '¿Esta seguro que desea ocultar el registro?',
            'ALL_FIELDS_ARE_REQUIRED': 'Todos los campos son obligatorios',
            'ALL_FILES_CORRESPONDING_TO_THE_SAME_STUDY_MUST_BE_OF_THE_SAME_TYPE_AND_SIZE': 'IMPORTANTE: Todos los archivos correspondientes a un mismo estudio, deben ser del mismo TIPO y TAMAÑO. Sólo se pueden cargar múltiples archivos si son secuencias DICOM, de lo contrario, sólo un archivo a la vez',
            'BACK': 'Atrás',
            'BACK_TO_REPORT': 'Volver al reporte',
            'BACKGROUND': 'Antecedentes',
            'BILLIAR_DISEASES': 'Enfermedad biliar',
            'BIRTHDATE': 'Fecha de Nacimiento',
            'BOTH': 'Ambos',
            'BRIGHTNESS': 'Brillo',
            'CALLCENTER': 'CallCenter',
            'CANCER': 'Cáncer',
            'CHICKENPOX': 'Varicela',
            'CITY': 'Ciudad',
            'CANCEL': 'Cancelar',
            'CANCEL_AND_RETURN_TO_THE_REQUEST': 'Cancelar y regresar a la consulta',
            'CANCEL_AND_RETURN_TO_THE_REPORT': 'Cancelar y regresar al reporte',
            'Cancelled': 'Cancelado',
            'cancelled': 'Cancelado',
            'CANCEL_CALL': 'Cancelar Llamada',
            'CANCEL_PROCEDURE_REQUEST': 'Cancelar Solicitud',
            'CARDIOVASCULAR_APPARATUS': 'Aparato Cardiovascular',
            'CATHARSIS': 'Catarsis',
            'CDM_STUDY': 'Estudio CDM',
            'CHECK_ALL_THE_OPTIONS_FOR_THE_PATIENT_IN_QUESTION': 'Marque todas las opciones correspondientes al paciente en cuestión.',
            'CHEST': 'Torax',
            'CHILLHOOD_DISEASES': 'Enfermedades de la infancia',
            'CLEAR': 'Limpiar',
            'CLICK_TO_SEE_REQUEST': 'Click para ver la solicitud',
            'CLICK_TO_SEE_PATIENT': 'Click para ver el paciente',
            'CLICK_TO_SEE_NOTIFICATIONS': 'Click para ver las notificaciones',
            'CLIENT': 'Cliente',
            'CLOSE': 'Cerrar',
            'CONTACT': 'Contacto',
            'CONCLUSION': 'Conclusión',
            'CONCLUSION_IS_REQUIRED': 'La conclusión es requerida',
            'CONFIRM_CANCEL_CALL': 'Confirmar cancelación de llamada',
            'CONFIRM_CANCEL_PROCEDURE_REQUEST': 'Confirmar cancelaciòn de solicitud',
            'CONFIRM_REJECT_PROCEDURE_REQUEST': 'Confirmar rechazo de solicitud',
            'CONFIRM_RESEND_PROCEDURE': 'Confirmar reenvio de la solicitud',
            'CONFIRM_REVISION_DIAGNOSTIC': 'Confirmar revisión',
            'CONTRAST': 'Contraste',
            'COMMENT': 'Comentar',
            'COMMENTS': 'Comentarios',
            'COMMENTED': 'Comentado',
            'commented': 'Comentado',
            'COMPLETED': 'Finalizado',
            'completed': 'Finalizado',
            'COMPLETE_SECTIONS_OF_THE_FORM_AND_PRESS_SAVE_TO_SEND_AND_RECEIVE': 'Complete las secciones del formulario y luego presione Guardar para enviarlo y ser atendido',
            'COMPLETE_WITH_A_SHORT_TEXT_ONLY_THE_FIELDS_THAT_REQUIRE_IT': 'Complete con un breve texto sólo los campos que así lo requieran.',
            'COUNTRY': 'País',
            'COORDINATOR': 'Coordinador',
            'CREATE': 'Crear',
            'CREATE_DIAGNOSTIC': 'Crear Solicitud',
            'CREATED': 'Creado',
            'CREATE_NEW_STUDIE': 'Crear Nuevo estudio',
            'CREATED_AT': 'Fecha de Creación',
            'CREATE_ONLY_FROM_THE_CDM': 'Crear solo desde el CDM',
            'CREATE_PROCEDURE_FOR_NEW_PATIENT': '¿Quiere crear una nueva solicitud para el paciente?',
            'CREDIT': 'Crédito',
            'DATA_STRUCTURE': 'Estructura de Datos',
            'DAY_S': 'D',
            'DAY_M': 'L',
            'DAY_T': 'M',
            'DAY_W': 'X',
            'DAY_TH': 'J',
            'DAY_F': 'V',
            'DAY_SA': 'S',
            'DATE': 'Fecha',
            'DELETE': 'Eliminar',
            'DEVICE': 'Dispositivo',
            'DESCRIPTION': 'Descripción',
            'DESTINATION_ORGANIZATION': 'Organizacion destino',
            'DERIVE': 'Derivar',
            'DIABETES': 'Diabetes',
            'DIAGNOSTIC_ORDER': 'Solicitud',
            'DIAGNOSTIC_ORDER_CORRESPONDING_TO': 'Solicitud correspondiente a',
            'DIAGNOSTIC_ORDERS': 'Solicitudes',
            'DIAGNOSTIC_ORDERS_AND_DIAGNOSTIC_REPORTS': 'Solicitudes y Reportes',
            'DIAGNOSTIC_ORDER_QUANTITY': 'Cantidad de solicitudes',
            'DIAGNOSTIC_REPORT': 'Reporte',
            'DIAGNOSTIC_REPORTS': 'Reportes',
            'DIAGNOSTIC_REPORTS_ARE_MADE_FROM_DIAGNOSTIC_ORDERS': 'Los reportes se realizan desde la sección ',
            'DIAGNOSTIC_ORDERS_ARE_MADE_FROM_PATIENTS': 'Las solicitudes se realizan desde la sección ',
            'DIAGNOSTIC_REPORT_QUANTITY': 'Cantidad de reportes',
            'DICOM_VIEWER': 'Visor Dicom',
            'DIET': 'Dieta',
            'DIGESTIVE_HEMORRHAGE': 'Hemorragia Digestiva',
            'DIPHTERIA': 'Difteria',
            'DISTRICT': 'Distrito',
            'DISCARD': 'Descartar',
            'DIURESIS': 'Diuresis',
            'DISEASES_OF_HORIZONTAL_TRANSMISSION': 'Enfermedades de transmisión horizontal',
            'DROP': 'Gota',
            'DONE': 'HECHO',
            'EAR': 'Oido',
            'EMAIL': 'Email',
            'EMAIL_ALREADY_EXISTS': 'El email ya existe.',
            'EDIT': 'Editar',
            'EDIT_DIAGNOSTIC': 'Editar Solicitud',
            'EDIT_USER': 'Editar Usuario',
            'EDIT_PROFILE': 'Editar Perfil',
            'ENCOUNTER': 'Encuentro',
            'END_PROCEDURE': 'Finalizar Solicitud',
            'ENTER': 'ENTER',
            'EMERGENCY_SYNCHRONOUS_CONSULTATION': 'Consulta Sincrónica de Emergencia',
            'ERROR_CREATING_USER':'Error al crear usuario',
            'ERROR_USER_PASS': 'El usuario y constraseña son obligatorios, además deben contener sólo caracteres alfanúmericos y cumplir con las longitudes.',
            'ERROR_PASS_REPEAT_PASS': 'Las contraseñas no coinciden. Por favor vuelva a intentarlo.',
            'ERROR_INVALID_EMAIL':'Error email invalido.',
            'EPILEPSY': 'Epilepsia',
            'EXIT': 'Salir',
            'EXITING_THIS_SCREEN_WILL_CAUSE_CANCELLATION_IN_THE_COURSE_DO_YOU_CONFIRM_THE_EXIT': 'Salir de esta pantalla provocará la cancelación en el curso. ¿Confirma la salida?',
            'ETS': 'ETS',
            'EYES': 'Ojos',
            'EXIT_STUDY_UPLOAD': 'Salir de la carga de estudios.',
            'EXTENSION_DESCRIPTION': 'En un consulta sincronica podras compartir tu pantalla en la videoconferencia para que los invitados puedan verla. (Se requiere que se instale la siguiente extension para tu navegador(google chrome)). Luego de instalar la extensión en la videoconferencia aparecera el boton "Compartir pantalla" automaticamente.',
            'FACE_AND_HEAD': 'Cara y Cabeza',
            'FAMILY_HISTORY': 'Historia Familiar',
            'FEEDING': 'Alimentacion',
            'FEMALE': 'Femenino',
            'FILE': 'Archivo',
            'FINALIZE': 'Finalizar',
            'FINISH_AND_CLOSE_DIAGNOSTIC': 'Finalizar y cerrar consulta',
            'FINISH_DATE': 'Fecha de finalización',
            'FILES': 'Archivos',
            'FILE_NO_DICOM_ERROR_IN_LIST': 'SOLO SE PUEDEN ADJUNTAR MULTIPLES ARCHIVOS SI SON UNA SECUENCIA DICOM, para Archivos de distinto tipo, por favor adjunte un archivo por estudio',
            'FRIDAY': 'Viernes',
            'GENERAL_DATA': 'Datos Generales',
            'GENERAL_INSPECTION': 'Inspección General',
            'GENERAL_ADMINISTRATOR': 'Administrator General(dios)',
            'GENDER': 'Género',
            'GO_TO_LIST': 'Volver al listado',
            'HOME': 'Inicio',
            'HELP': 'Ayuda',
            'HEPATITIS': 'Hepatitis',
            'HEPATITIS_A': 'Hepatitis A',
            'HEPATITIS_B': 'Hepatitis B',
            'HEPATITIS_C': 'Hepatitis C',
            'HEPATITIS_D': 'Hepatitis D',
            'HIGH': 'Alta',
            'HIDE': 'Ocultar',
            'HTA': 'HTA',
            'IDENTIFIER': 'Identificador',
            'IF_YOU_SELECT_ASYNCHRONOUS_MODE_YOU_WILL_BE_NOTIFIED_WHEN_YOU_RECEIVE_A_WRITTEN_REPORT_OF_YOUR_REQUEST': 'Si selecciona el MODO ASINCRÓNICO, se le notificará cuando reciba un reporte escrito de su solicitud',
            'IF_IT_IS_ACCEPTED_DATA_WILL_BE_PERMANENTLY_DELETED': 'Si acepta se eliminarán datos de forma permanente.',
            'IF_NECESSARY_ADD_A_NOTE_TO_THE_MEDICAL_PROVIDER': 'Si es necesario, agregue una nota para el médico prestador de servicio.',
            'IT_CAN_ALREADY_BE_ATTENDED': 'Ya puede ser atendido',
            'ILICIT_DRUGS': 'Drogas Ilícitas',
            'INIT_CALL': 'Iniciar Llamada',
            'INCLUDES_VIDEO_CALL': 'Incluye video llamada',
            'INVALID_PASSWORD': 'Contraseña incorrecta',
            'TO_SEARCH_INSERT_DNI_OR_NAME_OF_PATIENT_AND_PRESS_ENTER': 'Busque por NOMBRE o DNI del paciente y presione ENTER',
            'INSERT_THE_NAME_OF_A_REGISTERED_PATIENT_TO_BEGIN_THE_APPLICATION': 'Inserte el nombre o DNI de un paciente registrado para comenzar con la solicitud. (Minimo 3 caracteres).',
            'IT_IS_NECESSARY_TO_CREATE_AN_ORGANIZATION_FIRST': 'Es necesario crear una organización primero.',
            'IT_IS_NECESSARY_THAT_THE_PRACTITIONER_HAVE_SPECIALTY_AND_ORGANIZATION': 'Es necesario que el profesional tenga especialidad y organización',
            'IT_IS_NOT_POSSIBLE_TO_ANSWER': 'No es posible responder',
            'ITU': 'ITU',
            'LAST_DIAGNOSTIC_ORDERS_AND_DIAGNOSTIC_REPORTS': 'Ultimas Solicitudes y Reportes',
            'LATEST_NOTIFICATIONS_RECEIVED': 'Últimas notificaciones recibidas',
            'LENDER': 'Prestador',
            'LENDER_ORGANIZATION': 'Organización Prestadora',
            'LINE': 'Dirección',
            'LIST': 'Listado',
            'LIST_OF_MY_DIAGNOSTIC_REPORTS': 'Listados de mis reportes',
            'LIST_OF_MY_DIAGNOSTIC_ORDERS': 'Listados de mis solicitudes',
            'LOCATION': 'Locación',
            'LOGIN': 'Iniciar Sesión',
            'LOGOUT': 'Cerrar Sesión',
            'LOW': 'Baja',
            'LUPUS': 'Lupus',
            'MADE_BY': 'Realizado por',
            'MALARIA': 'Malaria',
            'MANAGING_ORGANIZATION': 'Organización de gestión',
            'MEASLES': 'Paperas',
            'MESSAGE': 'Mensaje',
            'MEDIUM': 'Media',
            'MINIMUM_LENGTH_4_CHARACTERS': 'Longitud minima 4 caracteres alfanumericos.',
            'MINIMUM_LENGTH_8_CHARACTERS': 'Longitud minima 8 caracteres alfanumericos.',
            'MALE': 'Masculino',
            'MIX': 'Mixto',
            'MODIFICATIONS': 'Modificaciones',
            'MORE_RESULTS': 'Mas resultados',
            'MODIFIED_AT': 'Fecha de modificación',
            'MONDAY': 'Lunes',
            'MONTH_SHORT_JAN': 'ENE',
            'MONTH_SHORT_FEB': 'FEB',
            'MONTH_SHORT_MAR': 'MAR',
            'MONTH_SHORT_APR': 'ABR',
            'MONTH_SHORT_MAY': 'MAY',
            'MONTH_SHORT_JUN': 'JUN',
            'MONTH_SHORT_JUL': 'JUL',
            'MONTH_SHORT_AUG': 'AGO',
            'MONTH_SHORT_SEP': 'SEP',
            'MONTH_SHORT_OCT': 'OCT',
            'MONTH_SHORT_NOV': 'NOV',
            'MONTH_SHORT_DEC': 'DIC',
            'MONTH_JANUARY': 'Enero',
            'MONTH_FEBRUARY': 'Febrero',
            'MONTH_MARCH': 'Marzo',
            'MONTH_APRIL': 'Abril',
            'MONTH_MAY': 'Mayo',
            'MONTH_JUNE': 'Junio',
            'MONTH_JULY': 'Julio',
            'MONTH_AUGUST': 'Agosto',
            'MONTH_SEPTEMBER': 'Septiembre',
            'MONTH_OCTOBER': 'Octubre',
            'MONTH_NOVEMBER': 'Noviembre',
            'MONTH_DECEMBER': 'Diciembre',
            'MOUTH': 'Boca',
            'MUMPS': 'Asma',
            'MY_REPORTS': 'Mis Reportes',
            'MY_NOTIFICATIONS': 'Mis Notificaciones',
            'NAME': 'Nombre',
            'NAME_IS_REQUIRED': 'El nombre es requerido',
            'NECK': 'Cuello',
            'NERVOUS_SYSTEM': 'Sistema Nervioso',
            'NEW': 'Nuevo',
            'NEW_A': 'Nueva',
            'NEW_ASYNCHRONOUS_CONSULTATION': 'Nueva Consulta Asincrónica',
            'NEW_DIAGNOSTIC_ORDER': 'Nueva solicitud',
            'NEW_DIAGNOSTIC_REPORT': 'Nuevo reporte',
            'NEW_NODE_ADMINISTRATOR': 'Nuevo Administrador de Nodos',
            'NEW_ORDER': 'Nueva Solicitud',
            'NEW_ORGANIZATION': 'Nueva Organización',
            'NEW_ORGANIZATION_ADMINISTRATOR': 'Nuevo Administrador Organizaciones',
            'NEW_PRACTITIONER': 'Nuevo Profesional de la salud',
            'NEW_STUDY': 'Nuevo Estudio',
            'NEW_USER': 'Nuevo Usuario',
            'NEW_USER_CREATED': 'Nuevo usuario creado',
            'NEW_REPORT': 'Nuevo reporte',
            'NEW_SYNCHRONOUS_CONSULTATION': 'Nueva consulta Sincrónica',
            'NEW_EMERGENCY_SYNCHRONOUS_CONSULTATION': 'Nueva consulta Sincrónica de Emergencia',
            'NEW_SCHEDULED_SYNCHRONOUS_CONSULTATION': 'Nueva consulta Sincrónica Programada',
            'NEW_SCHEDULED_SYNCHRONOUS_CONSULTATION_WITH_PATIENT_PRESENT': 'Nueva consulta Sincrónica Programada con Paciente',
            'NEW_SPONTANEOUS_SYNCHRONOUS_CONSULTATION': 'Nueva consulta Sincrónica Espontánea',
            'NEW_URGENCY_SYNCHRONOUS_CONSULTATION': 'Nueva consulta Sincrónica de Urgencia',
            'NO': 'No',
            'NO_CANCEL_AND_RETURN_TO_THE_REQUEST': 'No,cancelar y seguir con la consulta',
            'NODE_ADMINISTRATOR': 'Administrador de Nodos',
            'NOTES': 'Notas',
            'NOTESMAY': 'NOTAS',
            'NOTE': 'Nota',
            'NOTIFICATIONS': 'Notificaciones',
            'NOTIFICATIONS_LIST': 'Listado de notificaciones',
            'NOTIFICATION_VIEW': 'Vista de la notificación',
            'NONE': 'Ninguna',
            'NONE_M': 'Ninguno',
            'NOSE': 'Nariz',
            'NO_RECORDS_FOUND': 'No hay registros',
            'NO_PATIENTS_WERE_FOUND_FOR_THIS_DNI': 'No se encontraron pacientes para este dni. ',
            'NO_PATIENTS_WERE_FOUND': 'No se encontraron pacientes. ',
            'OTHERS': 'Otros',
            'OBESITY': 'Obesidad',
            'OBSERVATION': 'Observacion',
            'OBSERVATIONS': 'Observaciones',
            'OLD': 'Antiguo',
            'OSTEOMYOARTICULAR_SYSTEM': 'Sistema Osteomioarticular',
            'ORGANIZATION ADMIN': 'Administrador de la Organización',
            'ORGANIZATION': 'Organización',
            'ORGANIZATION_NAME': 'Nombre de la Organización',
            'ORGANIZATIONS': 'Organizaciones',
            'ORGANIZATION_ADMINISTRATOR': 'Administrador de Organizaciones',
            'ORGANIZATION_IS_REQUIRED': 'La organización es requerida',
            'ORGANIZATION_ROLE': 'Rol de organización',
            'ORGANIZATION_TYPE': 'Tipo de Organización',
            'OTHER': 'Otro',
            'OTHER_DISEASES': 'Otras enfermedades',
            'PANCREATITIS': 'Pancreatitis',
            'PALUDISM': 'Paludismo',
            'PAUSE': 'Pausar',
            'PATIENT': 'Paciente',
            'PATIENT_GENERAL_DATA': 'Datos generales del paciente',
            'PATIENT_FORM': 'Formulario de paciente',
            'PATIENTS': 'Pacientes',
            'PATIENT_LIST': 'Listado de Pacientes',
            'PATHOLOGICAL_ANTECEDENTS': 'Antecedentes Patologicos',
            'PARASITISM': 'Parasitismo',
            'PARENT_ORGANIZATION': 'Organización Padre',
            'PAROTITIS_ADULTHOOD': 'Parotiditis',
            'PAROTITIS_CHILLHOOD': 'Parotiditis',
            'PART_OF': 'Organización de la que depende',
            'PASSWORD': 'Contraseña',
            'PEPTIC_ULCER': 'Úlcera Péptica',
            'PERFORMER': 'Creador',
            'PERSONAL_IDENTIFICATION': 'D.N.I.',
            'PERSONAL_HISTORY': 'Historia Personal',
            'PHONE': 'Telefono',
            'PHYSICAL': 'Física',
            'PNEUMONIA': 'Neumonia',
            'POSTAL': 'Postal',
            'PRACTITIONER': 'Profesional de la salud',
            'PRACTITIONER_LIST': 'Lista de profesionales de la salud',
            'PRACTITIONERS': 'Profesionales de la salud',
            'PHYSICAL_EXAM': 'Examen Físico',
            'PRIORITY': 'Prioridad',
            'PRINT': 'Imprimir',
            'PRINCIPAL': 'Principal',
            'PROCEDURE': 'Solicitud',
            'PROCEDURE_DATE': 'Fecha de la solicitud',
            'PROCEDURE_CREATION': 'Creación de la solicitud',
            'PROCEDURE_REASON': 'Motivo de la consulta',
            'PROCEDURE_REFRESH': 'Actualización de la consulta',
            'PROCEDURE_RESPONSE': 'Respuesta de la solicitud',
            'PROCEDURE_REQUEST_GENERATED': 'Solicitud generada',
            'PROCEDURE_REQUEST_EDITED': 'Solicitud editada',
            'PROCEDURE_TYPE': 'Tipo de solicitud',
            'POLE': 'Polo',
            'POSTAL_CODE': 'Código Postal',
            'PLAN': 'Plan',
            'PLAY': 'Reproducir',
            'PHYSIOLOGIC_HABITS': 'Hábitos Fisiológicos',
            'REASON': 'Motivo',
            'REASON_IS_REQUIRED': 'El motivo es obligatorio',
            'REASON_OPTIONAL': 'Motivo (opcional)',
            'REFERENCE': 'Referencia',
            'REPEAT_PASSWORD': 'Repetir Contraseña',
            'REPORT_GENERATED': 'Reporte Generado',
            'REPORT_LIST': 'Listado de Reportes',
            'REPORT_CREATION': 'Creación del reporte',
            'REPORT_MODIFICATION': 'Modificación del reporte',
            'REPLY': 'Responder',
            'REQUESTEDBY': 'Solicitado por',
            'REQUESTED_BY': 'Solicitado por',
            'REQUEST_REJECTED': 'Solicitud rechazada',
            'REQUEST_WITHOUT_STUDIES': 'Solicitud sin estudios',
            'REQUESTED': 'Solicitado',
            'requested': 'Solicitado',
            'RESEND': 'Reenviar',
            'RESEND_TO_OTHER_LENDER': 'Reenviar a otro prestador',
            'RESPIRATORY_SYSTEM': 'Aparato Respiratorio',
            'REVISION': 'revisión',
            'REVISION_AND_RESEND_THE_SAME_LENDER': 'Revisar y reenviar al mismo prestador',
            'TYPES_REQUESTS': 'Tipos de Solicitudes',
            'TYPHOID_FEVER': 'Fiebre Tifoidea',
            'TRANSFERRED_CALL': 'Llamada Transferida',
            'READED': 'Estado',
            'received': 'Recibido',
            'RECORD': 'Grabar',
            'RECORD_AND_SEND': 'Grabar y enviar',
            'RECORD_AND_SEND_REPORT': 'Grabar y enviar reporte',
            'REQUEST': 'Solicitud',
            'REQUEST_REFERENCE': 'Referencia a la solicitud',
            'REQUESTED_SPECIALITY': 'Especialidad solicitada',
            'REJECT': 'Rechazar',
            'REJECTED': 'Rechazado',
            'rejected': 'Rechazado',
            'REJECT_CALL': 'Rechazar llamada',
            'REJECT_AND_RESEND': 'Rechazar y reenviar',
            'REJECT_PROCEDURE_REQUEST': 'Rechazar Solicitud',
            'RESEND_PROCEDURE': 'Reenviar Solicitud',
            'REJECT_REASON': 'Razón del rechazo',
            'RESTART': 'Reiniciar',
            'RESTART_TONES': 'Reiniciar Tonos',
            'RETRY_CALL':'Reintentar llamada',
            'RESULT': 'Resultado',
            'RETURN_TO_LIST': 'Ir al listado',
            'REUMATHIC_FEVER': 'Fiebre Reumática',
            'revision': 'Revisión',
            'ROLE': 'Rol',
            'ROUTINE': 'Rutina',
            'RUBELLA': 'Rubiola',
            'SAVE': 'Guardar',
            'SAVE_AND_CONTINUE': 'Grabar y Continuar',
            'SAVE_AND_EXIT': 'Grabar y Salir',
            'SAVE_AND_SEND_REPORT': 'Grabar y enviar reporte',
            'SAVE_AND_NEW_PROCEDURE_REQUEST': 'Guardar y nueva solicitud',
            'SAVE_CHANGES': 'Guardar cambios',
            'SATURDAY': 'Sábado',
            'SEARCH_BY_NAME_OR_DNI_MINIMUN_3_CHARACTERES': 'Busque por nombre o DNI, minimo 3 caracteres.',
            'SELECT_THE_STATUS_OF_THE_REQUEST': 'Selecciona el Estado de la Solicitud',
            'SELECTING_THE_SYNCHRONOUS_MODE_WILL_BE_REDIRECTED_TO_A_VIDEO_CALL_WITH_THE_MEDICAL_SERVICE_PROVIDER': 'Si selecciona el MODO SINCRÓNICO será redirigido a una videollamada con el médico prestador de servicio. ',
            'SIGNUP': 'Regístrarse',
            'SPECIALTY': 'Especialidad',
            'SPECIALTIES': 'Especialidades',
            'SMOKING': 'Tabaquismo',
            'START_CALL': 'Iniciar Llamada',
            'START': 'Comenzar',
            'IN_VIDEO_CALL': 'en la videoconferencia',
            'INSERT_DNI_OF_PATIENT_AND_PRESS_ENTER': 'Ingrese el dni del paciente que desea buscar y presione la tecla Enter',
            'INSERT_DNI_OR_NAME_OF_PATIENT': 'Ingrese dni o nombre del paciente que desea buscar',
            'INSERT_YOUR': 'Ingrese su',
            'IN_THIS_SECTION_YOU_CAN_ATTACH_ALL_PATIENT_STUDIES_RELEVANT_TO_THE_APPLICATION_AND_OR_THE_POSSIBILITY_OF_GENERATING_STUDIES_IF_WORKING_FROM_A_CDM': 'En ésta sección se podrán adjuntar todos los estudios del paciente pertinentes a la solicitud y/o la posibilidad de generar estudios (en caso de estar trabajando desde un CDM).',
            'IN_THIS_SECTION_YOU_CAN_VIEW_ALL_PATIENT_STUDIES_RELEVANT_TO_THE_APPLICATION_AND_OR_THE_POSSIBILITY_OF_GENERATING_STUDIES_IF_WORKING_FROM_A_CDM': 'En ésta sección se podrán ver todos los estudios del paciente pertinentes a la solicitud y/o la posibilidad de generar estudios (en caso de estar trabajando desde un CDM).',
            'IMPORTANCE': 'Importancia',
            'IT_WILL_BE_ANSWERED_AS_SOON_AS_POSSIBLE': 'la misma será contestada a la brevedad',
            'SAVE_STUDY': 'Guardar Estudio',
            'SCARLATIN_FEVER': 'Fiebre Escarlatina',
            'SCHEDULED_SYNCHRONOUS_CONSULTATION': 'Consulta Sincrónica Programada',
            'SCHEDULED_SYNCHRONOUS_CONSULTATION_WITH_PATIENT_PRESENT': 'Consulta Sincrónica Programada con paciente',
            'SEARCH': 'Buscar',
            'SELECT': 'Seleccionar',
            'SELECT_A_ROLE': 'Seleccione un rol.',
            'SCHEDULE': 'Calendario',
            'SKIN_FANERAS_AND_SUBCUTANEOUS_CELLULAR_TISSUE': 'Piel faneras y tejido celular subcutaneo',
            'SEE_EXTENSION': 'Ver Extensión',
            'SEE_LIST': 'Ver Listado',
            'SEE_PATIENT': 'Ver Paciente',
            'SEE_PATIENTS': 'Ver Pacientes',
            'SEE_PROFILE': 'Ver Perfil',
            'SEE_REQUESTS': 'Ver Solicitudes',
            'SEE_REQUEST': 'Ver Solicitud',
            'SEE_REPORTS': 'Ver Reportes',
            'SEE_REPORT': 'Ver Reporte',
            'SEE_DIAGNOSTIC_ORDERS': 'Solicitudes',
            'SELECT_FILES': 'Seleccionar Archivos',
            'SELECT_FILE': 'Seleccionar un Archivo',
            'SELECT_ORGANIZATION': 'Seleccionar Organización',
            'SELECT_YOUR_ROLE_WHICH_YOU_WANT_OPERATE': 'Seleccionar el rol con el cual desea operar',
            'SELECT_LOGIN_ORGANIZATION': 'Seleccionar la organización de inicio de sesión',
            'SELECT_PRIORITY': 'Seleccionar la prioridad',
            'SELECT_THE_TYPE_OF_DIAGNOSTIC_REQUESTED': 'Seleccione el tipo de orden solicitada',
            'SELECT_ONE_PATIENT_TO_START': 'Seleccione un paciente para comenzar',
            'SELECT_TYPE': 'Seleccionar rol',
            'SEND': 'Enviar',
            'SERVICE_TYPE': 'Tipo de servicio',
            'SHARE_SCREEN': 'Compartir pantalla',
            'SINUSITIS': 'Sinusitis',
            'SLEEP': 'Sueño',
            'SLICE': 'Diapositiva',
            'SLICES': 'Diapositivas',
            'SMALLPOX': 'Viruela',
            'SPECIALITY': 'Especialidad',
            'SPONTANEOUS_SYNCHRONOUS_CONSULTATION': 'Consulta Sincrónica',
            'STAT': 'Stat',
            'STATE': 'Provincia',
            'STATISTICS': 'Estadisticas',
            'STATISTICS_LIST': 'Lista de Estadisticas',
            'STATUS': 'Estado',
            'STATUS_OF_PROCEDURE_REQUEST': 'Estado de la solicitud',
            'STUDY_NAME': 'Nombre del Estudio',
            'STUDY_NAME_OPTIONAL': 'Nombre del Estudio (Opcional)',
            'STUDIES': 'Estudios',
            'STUDIESMAY': 'ESTUDIOS',
            'SUNDAY': 'Domingo',
            'SUBROLE': 'Sub Rol',
            'suspended': 'Respondiendo',
            'SUSPENDED': 'Respondiendo',
            'SYNCHRONOUS': 'Sincrónica',
            'SYNCHRONOUS_CONSULTATION': 'Consulta sincrónica',
            'THE_CONCLUSION_MUST_HAVE_A_MINIMUM_OF_10_CHARACTERS': 'La conclusión debe tener un minimo de 10 caracteres',
            'THE_REQUEST_WAS_RECORDED_AND_SENT_TO_THE_RECEIVER': 'La solicitud fue Grabada y enviada al receptor',
            'THIS_ACTION_WILL_SEND_THE_NOTE_FOR_CLARIFICATION_WITHOUT_GENERATING_A_REPORT': 'Esta acción Enviará la NOTA para su aclaración SIN GENERAR TODAVIA UN REPORTE',
            'THIS_FIELD_IS_CASE_SENSITIVE': 'Este campo es sensible a las mayúsculas',
            'THIS_REQUEST_IS_BEING_ANSWERED_AT_THIS_TIME': 'Esta solicitud está siendo respondida en este momento',
            'THIS_REQUEST__HAS_ALREADY_BEEN_ANSWERED': 'Esta solicitud ya fue respondida',
            'THIS_REQUEST_WAS_REJECTED_FOR_THE_CURRENT_REASON': 'Esta solicitud fue rechazada por el siguiente motivo',
            'TEMP': 'Temporal',
            'TEMPERATURE': 'Temperatura',
            'TELEPHONE_WORK': 'Teléfono del trabajo',
            'TELEPHONE_HOME': 'Teléfono domiciliario',
            'THE_REPORT_FOR_THE_PROCEDURE_TITLE_HAS_BEEN_SAVED': 'Se ha guardado el reporte para la solicitud con titulo',
            'THERE_ARE_UNSAVED_NOTES': 'Hay notas sin guardar. Oprima COMENTAR',
            'THIRST': 'Sed',
            'THURSDAY': 'Jueves',
            'TITLE': 'Título',
            'TITLE_IS_REQUIRED': 'El Título es obligatorio.',
            'TITLE_OPTIONAL': 'Título (opcional)',
            'TRANSFER_CALL': 'Transferir Llamada',
            'TREATMENT': 'Tratamiento',
            'TO_ATTACH': 'Adjuntar',
            'TODAY': 'Hoy',
            'TONSILLITIS': 'Amidalitis',
            'TO_PERFORM_A_SEARCH_BY_CREATION_DATE_YOU_MUS_ENTER_THE_SAME_IN_FORMAT': 'Para realizar una busqueda por fecha, debe ingresar la misma en formato DD/MM/AAAA.',
            'TOXIC_HABITS': 'Habitos Tóxicos',
            'TUBERCULOSIS': 'Tuberculosis',
            'TUESDAY': 'Martes',
            'TYPE': 'Tipo',
            'UNREADED': 'No leidas',
            'UPDATE_PASSWORD': 'Actualizar contraseña',
            'USERNAME': 'Nombre de Usuario',
            'USER_ALREADY_EXISTS': 'Error: El usuario ya existe.',
            'URGENT': 'Urgente',
            'URGENCY_SYNCHRONOUS_CONSULTATION': 'Consulta Sincrónica de Urgencia',
            'VIEW': 'Vista',
            'VIEW_PATIENT': 'Datos del Paciente',
            'VIEW_PRACTITIONER': 'Datos del Profesional',
            'VIEW_ORGANIZATION': 'Vista de la Organización',
            'VIEW_DIAGNOSTIC_ORDER': 'Vista de Solicitud',
            'VIEW_DIAGNOSTIC_REPORT': 'Vista de Reporte',
            'VIEW_NOTIFICATIONS_RECIEVED_PENDING_OR_ALREADY_READ': 'Permite ver las notificaciones recibidas, pendientes o ya leidas',
            'VIEW_USER': 'Vista de Usuario',
            'UPLOAD_FILES': 'Subir Archivos',
            'USERS': 'Usuarios',
            'USER_NOT_FOUND': 'Usuario no encontrado',
            'USE': 'Uso',
            'WAITING_VIDEOCALL':'Esperando videollamada',
            'WEIGHT': 'Peso',
            'WEDNESDAY': 'Miércoles',
            'WORK': 'Trabajo',
            'WRITE_YOUR_COMENT_HERE': 'Escriba su comentario aquí y presione ENTER',
            'WRITE_YOUR_COMENT': 'Escriba su comentario aquí',
            'WELCOME_TO_THE_SITE_YOUR_PASSWORD_WAS_UPDATED_CORRECTLY': 'Bienvenido al sitio, su contraseña fue actualizada correctamente',
            'WELCOME_TO_THE_SITE': 'Bienvenido al sitio',
            'YES': 'Si',
            'YES_EXIT': 'Si, salir',
            'YOU_CAN_CREATE_ONE_WITH_THIS_DATA_AND_EDIT_IT_TO_SEND_IT_TO_THE_SAME_ORGANIZATION': 'Puede REENVIAR esta solicitud creando una nueva con estos datos y editarla para enviarla a la misma organización o a otra',
            'YOU_FINALIZED_THIS_REQUEST': 'Usted finalizó esta solicitud',
            'YOU_HAVE_A_NEW_NOTIFICATION': 'Tenes una nueva notificación',
            'YOUR_REPORT_AND_PRESS_SAVE': 'su Reporte y presione Guardar',
            'YOUR_REQUEST_CONTINUES_ITS_PROCESS_AND_WILL_BE_RESOLVED_AS_SOON_AS_POSSIBLE': 'Su solicitud continúa su proceso y será resuelta a la brevedad',
            'YOU_MUST_ENTER_A_NAME': 'Debe ingresar un nombre',
            'YOU_SELECTED_AN_ASYNCHRONOUS_REQUEST': 'Usted seleccionó una solicitud asincrónica',
            'YOU_SELECTED_A_SYNCHRONOUS_REQUEST': 'Usted seleccionó una solicitud sincrónica con videollamada.',
            'YOU_MUST_SELECT_A_PATIENT_BEFORE_UPLOADING_A_STUDY': 'Debe seleccionar un paciente antes de cargar un estudios',
            'ZIP_CODE': 'Código postal',
            'ONE_OF_THE_REQUIRED_FIELDS_IS_MISSING': 'Falta uno de los campos obligatorios'
        });
});
